/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * About
 */
public class About {
  @SerializedName("product")
  private String product = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("versionName")
  private String versionName = null;

  public About product(String product) {
    this.product = product;
    return this;
  }

   /**
   * The descriptive product name.
   * @return product
  **/
  @ApiModelProperty(value = "The descriptive product name.")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public About version(String version) {
    this.version = version;
    return this;
  }

   /**
   * The fully-qualified version identifier, as a decimal separated numeric id.
   * @return version
  **/
  @ApiModelProperty(value = "The fully-qualified version identifier, as a decimal separated numeric id.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public About versionName(String versionName) {
    this.versionName = versionName;
    return this;
  }

   /**
   * The name of this release.
   * @return versionName
  **/
  @ApiModelProperty(value = "The name of this release.")
  public String getVersionName() {
    return versionName;
  }

  public void setVersionName(String versionName) {
    this.versionName = versionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    About about = (About) o;
    return Objects.equals(this.product, about.product) &&
        Objects.equals(this.version, about.version) &&
        Objects.equals(this.versionName, about.versionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(product, version, versionName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class About {\n");
    
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

