/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeploymentVersionDataSource
 */

public class DeploymentVersionDataSource {
  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public DeploymentVersionDataSource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the data source. Read-only property.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the data source. Read-only property.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeploymentVersionDataSource type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of data source. One of: \&quot;RightNow\&quot;, \&quot;MetadataOnlyService\&quot;, \&quot;WebService\&quot;, \&quot;Analysis\&quot;, or \&quot;AnalysisOutput\&quot;. Read-only property.
   * @return type
  **/
  @ApiModelProperty(value = "The type of data source. One of: \"RightNow\", \"MetadataOnlyService\", \"WebService\", \"Analysis\", or \"AnalysisOutput\". Read-only property.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentVersionDataSource deploymentVersionDataSource = (DeploymentVersionDataSource) o;
    return Objects.equals(this.name, deploymentVersionDataSource.name) &&
        Objects.equals(this.type, deploymentVersionDataSource.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentVersionDataSource {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

