/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * DeploymentLog
 */

public class DeploymentLog {
  @SerializedName("date")
  private DateTime date = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("updatedBy")
  private String updatedBy = null;

  @SerializedName("services")
  private List<String> services = null;

  @SerializedName("activeVersion")
  private Integer activeVersion = null;

  public DeploymentLog date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * The date and time at which the activation occurred.
   * @return date
  **/
  @ApiModelProperty(value = "The date and time at which the activation occurred.")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public DeploymentLog description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the activated or deactivated deployment version.
   * @return description
  **/
  @ApiModelProperty(value = "A description of the activated or deactivated deployment version.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DeploymentLog updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * The user name of the person performing the action.
   * @return updatedBy
  **/
  @ApiModelProperty(value = "The user name of the person performing the action.")
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  public DeploymentLog services(List<String> services) {
    this.services = services;
    return this;
  }

  public DeploymentLog addServicesItem(String servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<String>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * The services to which the deployment version has been activated. Any of \&quot;interview\&quot;, \&quot;webservice\&quot;, \&quot;javaScriptSessions\&quot;, and \&quot;mobile\&quot;.
   * @return services
  **/
  @ApiModelProperty(value = "The services to which the deployment version has been activated. Any of \"interview\", \"webservice\", \"javaScriptSessions\", and \"mobile\".")
  public List<String> getServices() {
    return services;
  }

  public void setServices(List<String> services) {
    this.services = services;
  }

  public DeploymentLog activeVersion(Integer activeVersion) {
    this.activeVersion = activeVersion;
    return this;
  }

   /**
   * The active deployment version, or empty if there is no active deployment version.
   * @return activeVersion
  **/
  @ApiModelProperty(value = "The active deployment version, or empty if there is no active deployment version.")
  public Integer getActiveVersion() {
    return activeVersion;
  }

  public void setActiveVersion(Integer activeVersion) {
    this.activeVersion = activeVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentLog deploymentLog = (DeploymentLog) o;
    return Objects.equals(this.date, deploymentLog.date) &&
        Objects.equals(this.description, deploymentLog.description) &&
        Objects.equals(this.updatedBy, deploymentLog.updatedBy) &&
        Objects.equals(this.services, deploymentLog.services) &&
        Objects.equals(this.activeVersion, deploymentLog.activeVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, description, updatedBy, services, activeVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentLog {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    activeVersion: ").append(toIndentedString(activeVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

