/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import oracle.opa.hub.client.model.UserCollection;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * User
 */

public class User {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("hubAdmin")
  private Boolean hubAdmin = null;

  @SerializedName("determinationsApi")
  private Boolean determinationsApi = null;

  @SerializedName("integrationUser")
  private Boolean integrationUser = null;

  @SerializedName("collections")
  private List<UserCollection> collections = null;

  public User userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public User email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public User fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public User password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public User status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public User hubAdmin(Boolean hubAdmin) {
    this.hubAdmin = hubAdmin;
    return this;
  }

   /**
   * Get hubAdmin
   * @return hubAdmin
  **/
  @ApiModelProperty(value = "")
  public Boolean getHubAdmin() {
    return hubAdmin;
  }

  public void setHubAdmin(Boolean hubAdmin) {
    this.hubAdmin = hubAdmin;
  }

  public User determinationsApi(Boolean determinationsApi) {
    this.determinationsApi = determinationsApi;
    return this;
  }

   /**
   * Get determinationsApi
   * @return determinationsApi
  **/
  @ApiModelProperty(value = "")
  public Boolean getDeterminationsApi() {
    return determinationsApi;
  }

  public void setDeterminationsApi(Boolean determinationsApi) {
    this.determinationsApi = determinationsApi;
  }

  public User integrationUser(Boolean integrationUser) {
    this.integrationUser = integrationUser;
    return this;
  }

   /**
   * Get integrationUser
   * @return integrationUser
  **/
  @ApiModelProperty(value = "")
  public Boolean getIntegrationUser() {
    return integrationUser;
  }

  public void setIntegrationUser(Boolean integrationUser) {
    this.integrationUser = integrationUser;
  }

  public User collections(List<UserCollection> collections) {
    this.collections = collections;
    return this;
  }

  public User addCollectionsItem(UserCollection collectionsItem) {
    if (this.collections == null) {
      this.collections = new ArrayList<UserCollection>();
    }
    this.collections.add(collectionsItem);
    return this;
  }

   /**
   * Get collections
   * @return collections
  **/
  @ApiModelProperty(value = "")
  public List<UserCollection> getCollections() {
    return collections;
  }

  public void setCollections(List<UserCollection> collections) {
    this.collections = collections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.userName, user.userName) &&
        Objects.equals(this.email, user.email) &&
        Objects.equals(this.fullName, user.fullName) &&
        Objects.equals(this.password, user.password) &&
        Objects.equals(this.status, user.status) &&
        Objects.equals(this.hubAdmin, user.hubAdmin) &&
        Objects.equals(this.determinationsApi, user.determinationsApi) &&
        Objects.equals(this.integrationUser, user.integrationUser) &&
        Objects.equals(this.collections, user.collections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, email, fullName, password, status, hubAdmin, determinationsApi, integrationUser, collections);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hubAdmin: ").append(toIndentedString(hubAdmin)).append("\n");
    sb.append("    determinationsApi: ").append(toIndentedString(determinationsApi)).append("\n");
    sb.append("    integrationUser: ").append(toIndentedString(integrationUser)).append("\n");
    sb.append("    collections: ").append(toIndentedString(collections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

