/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.api;

import oracle.opa.hub.client.ApiException;
import oracle.opa.hub.client.api.DeploymentsApi;
import oracle.opa.hub.client.model.Deployment;
import oracle.opa.hub.client.model.Deployments;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeploymentsApi
 */
@Ignore
public class DeploymentsApiTest {

    private final DeploymentsApi api = new DeploymentsApi();

    
    /**
     * Delete a deployment
     *
     * This operation will delete a deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDeploymentTest() throws ApiException {
        String deploymentName = null;
        api.deleteDeployment(deploymentName);

        // TODO: test validations
    }
    
    /**
     * Get a deployment
     *
     * This operation will get a deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentTest() throws ApiException {
        String deploymentName = null;
        Deployment response = api.getDeployment(deploymentName);

        // TODO: test validations
    }
    
    /**
     * Get one or more deployments
     *
     * This operation will get one or more deployments
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentsTest() throws ApiException {
        Deployments response = api.getDeployments();

        // TODO: test validations
    }
    
    /**
     * Insert one or more deployments
     *
     * This operation will insert one or more deployments
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertDeploymentsTest() throws ApiException {
        Deployments body = null;
        api.insertDeployments(body);

        // TODO: test validations
    }
    
    /**
     * Update a deployment
     *
     * This operation will update a deployment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDeploymentTest() throws ApiException {
        String deploymentName = null;
        Deployment body = null;
        Deployment response = api.updateDeployment(deploymentName, body);

        // TODO: test validations
    }
    
}
