/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.api;

import oracle.opa.hub.client.ApiException;
import oracle.opa.hub.client.api.DeploymentsDeploymentLogsApi;
import oracle.opa.hub.client.model.DeploymentLogs;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeploymentsDeploymentLogsApi
 */
@Ignore
public class DeploymentsDeploymentLogsApiTest {

    private final DeploymentsDeploymentLogsApi api = new DeploymentsDeploymentLogsApi();

    
    /**
     * Get one or more deployment logs
     *
     * This operation will get one or more deployment logs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentLogsTest() throws ApiException {
        String deploymentName = null;
        DeploymentLogs response = api.getDeploymentLogs(deploymentName);

        // TODO: test validations
    }
    
}
