/*
 * Hub Administration
 * This version of the API allows management of OPA Hub users, deployments, and version information.
 *
 * OpenAPI spec version: 12.2.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package oracle.opa.hub.client.api;

import oracle.opa.hub.client.ApiException;
import oracle.opa.hub.client.api.UsersApi;
import oracle.opa.hub.client.model.User;
import oracle.opa.hub.client.model.Users;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Delete a user
     *
     * This operation will delete a user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String userName = null;
        api.deleteUser(userName);

        // TODO: test validations
    }
    
    /**
     * Get a user
     *
     * This operation will get a user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String userName = null;
        User response = api.getUser(userName);

        // TODO: test validations
    }
    
    /**
     * Get one or more users
     *
     * This operation will get one or more users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        Users response = api.getUsers();

        // TODO: test validations
    }
    
    /**
     * Insert or replace one or more users
     *
     * This operation will insert or replace one or more users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertOrReplaceUsersTest() throws ApiException {
        Users body = null;
        api.insertOrReplaceUsers(body);

        // TODO: test validations
    }
    
    /**
     * Insert one or more users
     *
     * This operation will insert one or more users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertUsersTest() throws ApiException {
        Users body = null;
        api.insertUsers(body);

        // TODO: test validations
    }
    
    /**
     * Update one or more users
     *
     * This operation will update one or more users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsersTest() throws ApiException {
        Users body = null;
        Users response = api.updateUsers(body);

        // TODO: test validations
    }
    
}
